### ISSUE TITLE
Extended call instruction support

### ISSUE THREAD

**Issue by dthaler** [Alan-Jowett/bpf_conformance#60]
The conformance test only tests CALL instructions with src=0x0 not src=0x1 or 0x2

See https://github.com/dthaler/ebpf-docs/blob/update/isa/kernel.org/instruction-set.rst#142jump-instructions

**Comment by Alan-Jowett** [comment]
Proposal is to extend the call mnemonic as follows to distinguish between the three options:
```
call [helper] id
call local label
call system id
```
With helper being optional to allow existing tests to work.

If this is agreeable, I will extend the BPF assembler to support these mnemonics.

**Comment by dthaler** [comment]
Sounds ok to me
