### ISSUE TITLE
Missing atomic instruction tests with BPF_FETCH

### ISSUE THREAD

**Issue by dthaler** [Alan-Jowett/bpf_conformance#61]
Currently only about half of the atomic instructions have tests.  It is missing ones with BPF_FETCH.
https://github.com/dthaler/ebpf-docs/blob/update/isa/kernel.org/instruction-set.rst#atomic-operations

**Comment by Alan-Jowett** [comment]
Proposal is to extend the lock mnemonic with an optional fetch keyword:
```
lock [fetch] add register_and_offset, target_register
```
With the fetch keyword being optional.

If this is agreeable, I will extend the BPF assembler to support these mnemonics.

**Comment by dthaler** [comment]
That is ok, but you also need to support BPF_XCHG and BPF_CMPXCHG, which are new instructions that only work with BPF_FETCH.
