### ISSUE TITLE
Build failure while building the 'bpf_conformance' package using Visual Studio 2022

### ISSUE THREAD

**Issue by dv-msft** [Alan-Jowett/bpf_conformance#77]
The windows build fails when using the VS2022 build environment.

**Repro Steps:**
(Assumes pre-install of VS2022 build environment).

1. Per instructions in the README.md, run the commands ```make -S . -B build``` followed by ```cmake --build build``` to build the required ```bpf_conformance_runner.exe``` binary.

**Expected behavior**
The build should succeed, and the ```bpf_conformance_runner.exe``` binary should be present in the ```bpf_conformance\build\bin\Debug``` directory.

**Actual outcome**
The cmake --build build command terminates with this linker error:

```
bpf_conformance.vcxproj -> D:\wrk\bpf_conformance\build\lib\Debug\bpf_conformance.lib
LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc143-mt-gd-x64-1_80.lib' [D:\wrk\bpf_conformance\build\src\bpf_conformance_runner.vcxproj]
```

**Comment by Alan-Jowett** [comment]
Need to use [MSVC version](https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html) to determine which tool chain to use.
